language: node_js
node_js:
  - "8.14.0"

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

services:
  - postgresql

before_script:
  - psql -c 'drop database if exists assessment_app_test;' -U postgres
  - psql -c 'create database assessment_app_test;' -U postgres
  - NODE_ENV=test npx knex migrate:latest
  - NODE_ENV=test npx knex seed:run

addons:
  postgresql: "9.3"